# Basic
title: idlebook
subtitle: 但行好事，莫问前程
welcome_message: <a href="http://idlevbook.com" target="_blank">欢迎您的访问。</a>
description: 嗨，我是添书，一名 iOS 开发者,目前暂居深圳。
creator: <a href="http://idlevbook.com">@idlebook</a>

url: "http://idlevbook.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 工具, description: 我所使用的 app 们, url: '/Apps'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    mail: idlebook@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
